variable "pool_name" {
  description = "Storage pool name"
  type        = string
  default     = "default"
  nullable    = false
}

variable "vm_name" {
  description = "Virtual machine name"
  type        = string
  nullable    = false
}

variable "vm_memory" {
  description = "Virtual machine memory (MB)"
  type        = number
  default     = 512
  nullable    = false
}

variable "vm_vcpu" {
  description = "Virtual machine CPU #"
  type        = number
  default     = 1
  nullable    = false
}

variable "vm_disk_size" {
  description = "Virtual machine CPU #"
  type        = number
  default     = 5361393152
  nullable    = false
}

variable "bridge_name" {
  description = "Host bridge interface name"
  type        = string
  default     = "vmbr0"
  nullable    = false
}

variable "cloud_image_url" {
  description = "Cloud image URL"
  type        = string
  default     = "https://cloud-images.ubuntu.com/releases/23.10/release/ubuntu-23.10-server-cloudimg-amd64.img"
  nullable    = false
}

variable "system" {
  description = "System configuration"
  type = object({
    hostname        = string
    domain          = string
    timezone        = optional(string, "Europe/Paris")
    disable_root    = optional(bool, false)
    ssh_pwauth      = optional(bool, false)
    package_upgrade = optional(bool, true)
    packages        = optional(list(string), [ "" ])
  })
}

variable "users" {
  description = "System user accounts"
  type = map(object({
    shell               = optional(string, "")
    sudo                = optional(string, "")
    hashed_passwd       = optional(string, "!")
    lock_passwd         = optional(bool, false)
    ssh_authorized_keys = optional(list(string), [ "# Generated by Terraform" ])
  }))
}

variable "network_interfaces" {
  description = "Network interfaces configuration"
  type = map(object({
    addresses   = list(string)
    gateway4    = string
    gateway6    = string
    nameservers = list(string)
  }))
}
